[pytest]
markers =
    integration: marks tests as integration tests
filterwarnings =
    ignore:'_UnionGenericAlias' is deprecated:DeprecationWarning
    ignore:The 'timeout' parameter is deprecated:DeprecationWarning
    ignore:The 'verify' parameter is deprecated:DeprecationWarning
